
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ztbhwbkqiknsoqflofqr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_XtC1vNvKqq0ui0-tZ2sGDQ_SM9BotEs";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
